image: "rocker/verse:4.1.2"

stages:
 - download
 - site
 - regions
 - github

osp:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "osp"
    script:
      - R -e "install.packages(c('gert','zoo'))"
      - R -e "source('R/makefile_osp_live.R')"
    artifacts:
      paths:
        - data
        - raw_data
      expire_in: 3 days

vax:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "vax"
    script:
      - R -e "install.packages(c('gert','zoo','dygraphs','xts', 'DT', 'gridExtra','distill'))"
      - R -e "source('R/makefile_osp_vaccines.R')"
      #- git push github master
    artifacts:
      paths:
        - data
      expire_in: 1 day


mobility:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "mobility"
    script:
      - R -e "install.packages(c('gert'))"
      - R -e "source('R/makefile_mobility.R')"
   #   - git push github master
    artifacts:
      paths:
        - data
      expire_in: 1 day

update:
    stage: regions
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "osp"
    script:
      - R -e "install.packages(c('gert','COVID19','dygraphs','xts', 'DT', 'gridExtra','distill','EpiEstim','flexdashboard'))"
      - rm README.md
      - R -e "source('R/makefile_site.R')"
    artifacts:
      paths:
        - docs
      expire_in: 1 day

push:
    stage: github
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE =="osp"
    script:
      - R -e "install.packages(c('gert'))"
      - R -e "source('R/makefile_github.R')"
      - git push github master
