---
title: "Apie"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
data <- Sys.time()
```
Atnaujinama kas dieną. Paskutinis atnaujinimas `r data`. 

## Puslapio turinys

  - [Elementarioji statistika](stats.html)
  - [Efektyvusis R](Re.html)
  - [Europos šalių 14 dienų atvejai 100 tūkst. gyventojų](countries.html)
  - [Epidemijos bangų models (nebeatnaujinamas)](glme.html)
  - [Apibendrinto logistinio augimo modelis (nebeatnaujinamas)](glm.html)
  - [SEIR epidemiologinis modelis (nebeatnaujinamas)](SEIR.html)
  - [Modelių prognozių palyginimas (nebeatnaujinamas)](comparison.html)
  - [Apibendrinto augimo modelis (nebeatnaujinamas)](ggm.html)


## Papildoma informacija

Modeliai yra edukacinio pobūdžio, juos galima laisvai naudoti, bet jiems nesuteikiama jokia garantija.

Modeliai yra atnaujinami kas dieną su naujais duomenimis. Duomenys yra [čia](https://github.com/mpiktas/covid19lt/tree/master/data), o visas prognozes galite rasti [čia](https://github.com/mpiktas/covid19lt/tree/master/forecasts).

Modelių kodas yra `.Rmd` failuose. Puslapis su modeliais yra pergneruojamas kiekvieną dieną. Norint tai padaryti pačiam reikia:

  1. Parsisiųsti šitą [repozitoriją](https://github.com/mpiktas/covid19lt/).
  2. Atsidaryti [Rstudio](http://www.rstudio.com) projektą (`covid19lt.Proj`).
  3. Įsidiegti reikiamus [R](http://www.r-project.org) paketus (`dplyr`, `lubridate`, `tidyr`, `ggplot2`, `EpiEstim`,`deSolve`, `rmarkdown`, `distill`).
  4. Paleisti komandą `rmarkdown::render_site()`.
  5. Rezultatai, t.y. puslapis bus sudėtas į `docs` katalogą.
