---
title: "COVID-19 Lietuvoje"

site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
library(readr)
library(tidyr)
library(dygraphs)
library(xts)
library(lubridate)
library(DT)
library(htmltools)
```

```{r include=FALSE}
data <- Sys.time()
```
  - [Savivaldybių statistika](savivaldybes.html)    
  - [Europos šalių 14 dienų atvejai 100 tūkst. gyventojų](countries.html)
  - [Laboratorijų duomenys](stats.html)
  - [Efektyvusis R](Re.html)
  
Atnaujinta: `r data`. 

```{r, echo = FALSE}
aa <- read.csv("data/lt-covid19-aggregate.csv", stringsAsFactors = FALSE) %>% mutate(day = ymd(day))
last_day <- max(aa$day)
ltR <- dget("raw_data/effectiveR/ltR.R")
ag <- function(x)(c(x[1],diff(x)))
dt <- aa %>% mutate(incidence = ag(confirmed)) %>% select(day, confirmed, incidence) %>% mutate(day = ymd(day), w = ifelse(incidence == 0, 0, 1))
dtf <- dt
dt <- dt %>% filter(day >= "2020-03-11") %>% mutate(times = 1:n())

oo <- ltR$R %>% inner_join(dt %>% rename(t_end=times), by ="t_end") %>% select(day, R = `Mean(R)`, lwr = `Quantile.0.025(R)`,upr = `Quantile.0.975(R)`)
bb <- xts(oo %>% select(-day), order.by=ymd(oo$day))
dygraph(bb, main = "Efektyvus reprodukcinis skaičius R") %>% dySeries(c("lwr","R","upr"), label = "R") %>% dyRangeSelector()
```


```{r, echo = FALSE}
stt <- aa %>% select(day, confirmed, deaths, recovered) %>% pivot_longer(confirmed:recovered, "type")

xtt <- xts(aa %>% select(deaths, confirmed, recovered, -day), order.by =aa$day)

dygraph(xtt, main = paste("Suminiai atvejai:",max(aa$day))) %>%  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")) %>% dyRangeSelector()
```

```{r, echo = FALSE}
axtt <- xts(aa$incidence, order.by =aa$day)
colnames(axtt) <- "incidence"

axtt7 <- rollmean(axtt, 7, fill = NA, align = "right")
axtt14 <- rollmean(axtt, 14, fill = NA, align = "right")
colnames(axtt7) <- paste0(colnames(axtt7),"7")
colnames(axtt14) <- paste0(colnames(axtt14),"14")

a714 <- cbind(axtt, axtt7, axtt14)

dygraph(a714[, c("incidence", "incidence7","incidence14")], main = paste("Dieniniai atvejai ir slenkantys vidurkiai:",max(aa$day))) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(3,2,1)]) %>% dyRangeSelector
```

```{r, echo =FALSE}
labs <- read.csv("data/lt-covid19-laboratory-total.csv", stringsAsFactors = FALSE) %>% mutate(day = ymd(day))

lbt <- labs %>% group_by(day) %>% summarise(daily_tests = sum(tested_all))
ltt <- aa %>% mutate(daily_tests = ag(tested)) %>% select(day, daily_tests)

lct <- ltt %>% left_join(lbt %>% rename(laboratory_tests = daily_tests), by = "day") %>% 
    mutate(sam_daily_tests = daily_tests, 
           daily_tests = ifelse(is.na(laboratory_tests), sam_daily_tests, laboratory_tests))

tpd <- aa %>% select(day, confirmed) %>% left_join(lct, by = "day") %>% 
    mutate(incidence = ag(confirmed), normalized = incidence*100/daily_tests, 
           incidence14 = rollsum(incidence, k = 14, fill = NA, align = "right"),
           tests14 = rollsum(daily_tests, k = 14, fill = NA, align = "right"),
           normalized14 = incidence14*100/tests14
           )  
    
xtpd <- xts(tpd %>% select(normalized, normalized14), order.by = tpd$day)

dygraph(xtpd, main = paste("Atvejų skaičius tenkantis 100 testų", max(aa$day))) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[2:3]) %>% dyRangeSelector 
```


## Atvejų pasiskirstymas pagal amžių ir savivaldybes `r last_day` 

```{r}
agre <- read.csv("data/lt-covid19-age-region-incidence.csv", check.names =  FALSE) 

agre1 <- agre %>% filter(day == max(day)) %>% select(-day) 

regs_n <- paste0(gsub("[.]","",gsub(" ", "_",agre1$administrative_level_3)),".html")

links <- paste0("regions/", regs_n) 

links2 <- mapply(function(nm, hr) tags$a(href=hr, nm),  agre1$administrative_level_3, links, SIMPLIFY = FALSE)


agre2 <- agre1
agre2$administrative_level_3 <- sapply(links2,as.character)
agre2$administrative_level_3[nrow(agre2)] <- "Total"

agre2 <- agre2 %>% rename(Savivaldybė = administrative_level_3)
agre2 %>% datatable( 
         extensions = c('FixedColumns',"FixedHeader"),
          escape = FALSE,
          options = list(scrollX = TRUE, 
                         paging=FALSE,
                         fixedHeader=TRUE))
```

## Atvejų skaičiai savivaldybėse `r last_day`

Nuo liepos 1d.

```{r, echo=FALSE}
ii <- read.csv("data/lt-covid19-individual.csv")
ad <- ii %>% count(day,administrative_level_3) %>% mutate(day = ymd(day))

ggplot(aes(x=day, y = n ),
       data = ad %>% filter(day >= "2020-07-01", administrative_level_3 %in% (agre1 %>% pull(administrative_level_3)))) +
           facet_wrap(~administrative_level_3, scales = "free_y") +geom_line()
```