---
title: "Efektyvus R"
output: distill::distill_article
---

```{r, echo = FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(rmarkdown)
library(lubridate)
library(dygraphs)
library(xts)
options(max.print = 100000)
```

```{r include = FALSE}
data <- Sys.time()
```

Atnaujinta: `r data`. 

# Duomenys modeliavimui

```{r,  echo = FALSE}
dt <- read.csv("total/lt-covid19-total.csv", stringsAsFactors = FALSE)
ag <- function(x)(c(x[1],diff(x)))
dt <- dt %>% mutate(incidence = ag(confirmed)) %>% select(day, confirmed, incidence) %>% mutate(day = ymd(day), w = ifelse(incidence == 0, 0, 1)) 
dtf <- dt
dt <- dt %>% filter(day >= "2020-03-11") %>% mutate(times = 1:n())
paged_table(dt %>% select(-w))
```

```{r, echo = FALSE, message = FALSE, warning=FALSE}
library(EpiEstim)
incidence_data <- dt %>% select(date = day, I = incidence)
ltR <-  estimate_R(incidence_data,
                                  method="uncertain_si",
                                  config = make_config(list(
                                  mean_si = 4.8, std_mean_si = 3.0,
                                  min_mean_si = 2, max_mean_si = 7.5,
                                  std_si = 3.0, std_std_si = 1.0,
                                  min_std_si = 0.5, max_std_si = 4.0,
                                  n1 = 1000, n2 = 1000)))
```

# Savaitinis R įvertis. 

$R < 1$ reiškia kad epidemija perėjo į kritimą. Daryta pagal šitą [straipsnį](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3816335/) su R paketu [EpiEstim](https://cran.r-project.org/web/packages/EpiEstim/index.html). Daryta pagal pavyzdį iš šio [blogo](https://timchurches.github.io/blog/posts/2020-02-18-analysing-covid-19-2019-ncov-outbreak-data-with-r-part-1/#fitting-an-sir-model-to-the-hubei-province-data).



```{r, echo = FALSE}
oo<-ltR$R %>% inner_join(dt %>% rename(t_end=times), by ="t_end") %>% select(day, R = `Mean(R)`, lwr = `Quantile.0.025(R)`,upr = `Quantile.0.975(R)`)
bb <- xts(oo %>% select(-day), order.by=ymd(oo$day))
dygraph(bb, main = "Effective R in Lithuania") %>% dySeries(c("lwr","R","upr"), label = "R") %>% dyRangeSelector()
```

$x$-ašyje yra dienos nuo epidemijos pradžios. Epidemijos pradžia pasirinkta 2020-03-11, tai pirma diena. 

Ta pati informacija lentelėje

```{r,echo=FALSE}

RR <- ltR$R 

RR[,1] <- RR[,2]
RR[,2] <- dt$day[RR[,1]]

colnames(RR)[1:2] <- c("t_end", "day_end")

RR %>% paged_table
```


[Serijiniai intervalai](https://en.wikipedia.org/wiki/Serial_interval) (intervalai tarp užsikrėtimų)

```{r, echo = FALSE}
plot(ltR, what = "SI")
```