---
title: "COVID-19 statistika"
output: distill::distill_article
---

```{r, echo=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(readr)
library(tidyr)
tt <- read_csv("total/lt-covid19-total.csv") 
```

```{r include = FALSE}
data <- Sys.time()
```

Atnaujinta: `r data`. 


```{r, echo = FALSE}
stt <- tt %>% select(day, confirmed, deaths, recovered) %>% pivot_longer(confirmed:recovered, "type")
ggplot(aes(x = day, y = value, group = type, colour = type), data =stt) + geom_point()+geom_line()+labs(title = paste("Cumulative cases:",max(tt$day)))
```

```{r, echo = FALSE}
ag <- function(x)c(x[1],diff(x))
ntt <- stt %>% arrange(type, day) %>% group_by(type) %>%  mutate(value = ag(value)) %>% ungroup
ggplot(aes(x = day, y = value, group = type), data =ntt) + geom_col(aes(fill=type),position = "dodge",)+labs(title = paste("New cases:",max(tt$day)))
```


```{r, echo = FALSE}
ggplot(aes(x = day, y = tested), data = tt) +geom_point() + geom_line() + labs(title = paste("Cumulative tests:",max(tt$day)),  x = "tested")
```


```{r, echo = FALSE}
ggplot(aes(x = day, y = ag(tested)), data = tt) +geom_col() + labs(title = paste("Daily tests: ", max(tt$day)), y="tested")
```

```{r, echo = FALSE, fig.height=10, fig.width=10}
library(lubridate)
labs <- read.csv("tests/lt-covid19-laboratory-total.csv", stringsAsFactors = FALSE) %>% mutate(day = ymd(day))

labst <- labs %>% select(day, laboratory, tested_all, positive_all, not_tested) %>% pivot_longer(tested_all:not_tested, "type")


ggplot(aes(x = day, y = value, group = type), data = labst) + geom_col(aes(fill=type),position = "dodge")+ facet_wrap(~laboratory, scales = "free_y")+labs(title = paste("Laboratory tests:",max(tt$day)))
```


```{r, echo = FALSE}
labs <- labs %>% group_by(laboratory) %>% mutate(tested_all = ifelse(is.na(tested_all), 0, tested_all), capacity = 100*(tested_all/max(tested_all)))

ggplot(aes(x = day, y = capacity, group = laboratory) , data = labs) + geom_col(aes(fill=laboratory),position = "dodge")+ labs(title = paste("Laboratory capacity:",max(labs$day)))
```
