---
title: "EVRK analysis"
output: html_notebook
---

```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(zoo)
library(stringr)
evrk <- read.csv("../data/lt-covid19-evrk.csv") %>% mutate(day = ymd(day))
evrk_meta <- read.csv("../raw_data/osp/evrk_meta.csv")
Sys.setlocale(locale = "lt_LT.UTF-8")
```

```{r}

tt <- evrk %>% group_by(evrk_group_title, evrk_group_code ) %>% select(-day) %>% summarise_all(sum) %>% mutate(r = round(100*tests_positive/tests,2)) %>% arrange(tests) %>% ungroup
tt
```

```{r}
tt_month <- evrk %>% group_by(evrk_group_title, evrk_group_code, month = month(day)) %>% select(-day) %>% summarise_all(sum) %>% mutate(r = round(100*tests_positive/tests,2)) %>% arrange(tests) %>% ungroup

tt_month %>% filter(month == 11) %>% arrange(-tests)
```

```{r}
tt$tests %>% quantile(seq(0,1,by=0.1))

```

```{r}
evrk1 <- evrk %>% group_by(evrk_group_code) %>% arrange(day) %>% mutate(
    positive_sum7 = rollsum(tests_positive, 7, fill = NA, align = "right"),
    positive_sum14 = rollsum(tests_positive, 14, fill = NA, align = "right"),
    tests_sum7 = rollsum(tests, 7, fill = NA, align = "right"),
    tests_sum14 = rollsum(tests, 14, fill = NA, align = "right"),
    tpr7 = round(100*positive_sum7/tests_sum7, 2),
    tpr14 = round(100*positive_sum14/tests_sum14,2),
    tpr1 = round(100*tests_positive/tests,2)
)
```

```{r}
lv1 <- read.csv("../data/lt-covid19-country.csv") %>% mutate(day = ymd(day))
```

```{r}
top15 <- tt %>% arrange(-tests) %>% slice_head(n=15) %>% .$evrk_group_code
top16 <- tt %>% arrange(-tests) %>% slice_head(n=16) %>% .$evrk_group_code
cmp <- evrk1 %>% select(day, evrk_group_code, evrk_group_title, tpr = tpr7) %>% filter(evrk_group_code %in% top15)
lvt <- lv1 %>% select(day, tpr=tpr_dgn) %>% mutate(evrk_group_code = 0, evrk_group_title = "Lietuva")
cmp1 <- cmp %>% bind_rows(lvt)
cmp2 <- evrk1 %>%select(day, evrk_group_code, evrk_group_title, tpr = tpr7, tpr1 = tpr1) %>% filter(evrk_group_code %in% top16) %>% 
    inner_join(tt %>% select(evrk_group_code, total = tests)) %>% inner_join(lvt %>% select(day, tprl = tpr)) %>% mutate(veikla = paste0(str_trunc(evrk_group_title,30), " (", round(total/1000,1),"k)"))


svt <- evrk_meta %>% filter(evrk_chapter_code == 85) %>% .$evrk_group_code %>% unique

cmp3 <- evrk1 %>% select(day, evrk_group_code, evrk_group_title, tpr = tpr7, tpr1 = tpr1, tests_sum7) %>% filter(evrk_group_code %in% svt) %>% 
    inner_join(tt %>% select(evrk_group_code, total = tests)) %>% inner_join(lvt %>% select(day, tprl = tpr)) %>% mutate(veikla = paste0(str_trunc(evrk_group_title,30), " (", round(total/1000,1),"k)"))

```

```{r}
tt %>% filter(evrk_group_code %in% top16) %>% arrange(-tests) %>% select(evrk_group_title, tests)
```

```{r}
cols <- RColorBrewer::brewer.pal(3, "Set1")[c(1,2)]
names(cols) <- c("Lietuva","Veikla")

ggplot(aes(x = day, y = tpr, colour = "Veikla"), data = cmp2 %>% filter(day>="2020-12-01"))+geom_line()+facet_wrap(~veikla) + theme_bw()+labs(x = "Data", y = "Procentai", title = "Teigiamų testų dalis, 7 dienų vidurkis, top 16 testuojamų veiklų")+geom_line(aes(y = tprl, colour = "Lietuva")) + scale_colour_manual(name = "Spalva", values = cols)
```

```{r}
cols <- RColorBrewer::brewer.pal(3, "Set1")[c(1,2)]
names(cols) <- c("Lietuva","Veikla")

ggplot(aes(x = day, y = tpr1, colour = "Veikla"), data = cmp2 %>% filter(day>="2020-12-01"))+geom_line()+facet_wrap(~veikla) + theme_bw()+labs(x = "Data", y = "Procentai", title = "Teigiamų testų dalis, top 16 testuojamų veiklų")+geom_line(aes(y = tprl, colour = "Lietuva")) + scale_colour_manual(name = "Spalva", values = cols)
```

```{r}
wk2date <- function(year, week) {
    week[year == 2020] <- week[year == 2020]-1
    year[year == 2021 & week == 53] <- 2020
    week[week == 53] <- 52
    ymd(parse_date_time(paste(year, week, 1, sep="/"),'Y/W/u'))
}

vv <- evrk %>% mutate(wday = wk2date(year(day),isoweek(day))) %>% group_by(evrk_group_title, evrk_group_code, wday) %>% summarise(tests = sum(tests), r = round(100*sum(tests_positive)/sum(tests),2)) %>% mutate( levels = cut(r,c(0,5,10,15,20,25,100), include.lowest = TRUE))

vv1 <- vv %>% ungroup %>% count(wday,levels) %>% ungroup %>% group_by(wday) %>% mutate(p = round(100*n/sum(n),2))

vv2 <- vv %>% ungroup %>% filter(tests>=10) %>% count(wday, levels) %>% ungroup %>% group_by(wday) %>% mutate(p = round(100*n/sum(n),2))


vv3 <- vv2 %>% mutate(day = wday)
```

```{r}
ggplot(aes(x=day,y=p, fill=levels), data = vv3)+geom_col() + scale_fill_manual(name = "Intervalai", values = RColorBrewer::brewer.pal(6, "Set1")[c(3,2,4,6, 5,1)]) + theme_bw()+ labs(y = "Procentai", x = "Data", title = "EVRK veiklų teigiamų tyrimų dalis savaitėmis")
```

```{r}
ppt <- evrk %>% mutate(wday = wk2date(year(day),isoweek(day))) %>% group_by(wday) %>% summarise(tests_positive = sum(tests_positive), tests = sum(tests)) %>% arrange(wday) %>% mutate(r = round(100 * tests_positive/tests,2))

plv1 <- lv1 %>% mutate(wday = wk2date(year(day),isoweek(day))) %>% select(wday, tests_daily, tests_positive_daily) %>% group_by(wday) %>% summarize( tests_positive = sum(tests_positive_daily),tests = sum(tests_daily)) %>% mutate(r = round(100 * tests_positive/tests,2))

pp <- evrk %>% mutate(wday = wk2date(year(day),isoweek(day))) %>% group_by(profilaktika = evrk_group_code %in% c(861, 862), wday) %>% summarise(tests_positive = sum(tests_positive), tests = sum(tests)) %>% arrange(wday) %>% mutate(r = round(100 * tests_positive/tests,2))

ss
```
```{r}
ggplot(aes(x=wday, y= r, colour = profilaktika),data=pp)+geom_line()+theme_bw()
```

```{r}
pp1 <- pp %>% mutate(ligoninės = ifelse(profilaktika,"Taip","Ne"))
ggplot(aes(x=wday, y= tests, colour = ligoninės),data=pp1)+geom_line()+theme_bw() +labs(x = "Savaitės", y = "Testai", title = "Testavimo apimtys sveikatos priežiūros sektoriuje ir kitur") +scale_colour_manual(name = "Sveikatos įstaigos", values = RColorBrewer::brewer.pal(3,"Set1")[c(3,2)])
```


```{r}
cols <- RColorBrewer::brewer.pal(3, "Set1")[c(1,2)]
names(cols) <- c("Lietuva","Veikla")

ggplot(aes(x = day, y = tpr1, colour = "Veikla"), data = cmp3 %>% filter(day>="2021-01-01"))+geom_line()+facet_wrap(~veikla, scales = "free_y") + theme_bw()+labs(x = "Data", y = "Procentai", title = "Teigiamų testų dalis, švietimo sektoriaus veiklos")+geom_line(aes(y = tprl, colour = "Lietuva")) + scale_colour_manual(name = "Spalva", values = cols)
```

```{r}
cols <- RColorBrewer::brewer.pal(3, "Set1")[c(1,2)]
names(cols) <- c("Lietuva","Veikla")

ggplot(aes(x = day, y = tests_sum7, colour = "Veikla"), data = cmp3 %>% filter(day>="2020-12-01"))+geom_line()+facet_wrap(~veikla, scales = "free_y") + theme_bw()+labs(x = "Data", y = "Testai", title = "Testų 7 dienų slenkanti suma")+ scale_colour_manual( values = cols)

```