---
title: "Region stuff"
output: html_notebook
---

```{r}
lv3 <- read.csv("../data/lt-covid19-level3.csv") %>% mutate(day = ymd(day))

pl <- lv3 %>% select(day, administrative_level_2, administrative_level_3, confirmed_100k, tpr_dgn, confirmed_growth_weekly, population)

levs <- as.integer(c(0, 25, 100, 200, 300, 400, 500, 750, 1000, 3000))
pld0 <- pl %>%
  filter(administrative_level_3 != "Unknown") %>%
  mutate(Scenario = cut(confirmed_100k, levs, right = TRUE, include.lowest = TRUE))

pld1 <- pld0 %>% filter(day == max(day))
pld2 <- pld0 %>% filter(day == "2020-12-16")
pld3 <- pld0 %>%
  filter(day == "2020-09-01") %>%
  mutate(confirmed_growth_weekly, fixNA(confirmed_growth_weekly))

scen_c <- c("#fff5eb", "#fee6ce", "#fdd0a2", "#fdae6b", "#fd8d3c", "#f16913", "#d94801", "#a63603", "#7f2704")[2 + 1:4]
scen_d <- c("#fff5f0", "#fee0d2", "#fcbba1", "#fc9272", "#fb6a4a", "#ef3b2c", "#cb181d", "#a50f15", "#67000d")[7:9]
scen_a <- c("#4daf4a")
scen_b <- c("#ffff33")
cols <- c(scen_a, scen_b, scen_c, scen_d)
# cols <- RColorBrewer::brewer.pal(9,"Paired")
flevs <- levels(pld0$Scenario)
names(cols) <- flevs
```

```{r}
ggplot(aes(x = tpr_dgn, y = confirmed_growth_weekly, colour = Scenario, size = population), data = pld1) +
  geom_point() +
  geom_text(aes(label = administrative_level_3), size = 3, nudge_x = 0.8, check_overlap = TRUE) +
  theme_bw() +
  scale_colour_manual(name = "100k rodiklis", values = cols) +
  scale_size_continuous(name = "Populiacija") +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 4) +
  labs(x = "Teigiama tyrim킬 dalis, procentai", y = "Savaitinis augimas, procentai", title = paste("Lietuvos rodikliai,", max(pld1$day)))
```
```{r}
ggplot(aes(x = tpr_dgn, y = confirmed_100k, colour = Scenario, size = population), data = pld1) +
  geom_point() +
  geom_text(aes(label = administrative_level_3), size = 3, nudge_x = 0.8, check_overlap = TRUE) +
  theme_bw() +
  scale_colour_manual(name = "100k rodiklis", values = cols) +
  scale_size_continuous(name = "Populiacija") +
  geom_hline(yintercept = 100) +
  geom_vline(xintercept = 4) +
  labs(x = "Teigiama tyrim킬 dalis, procentai", y = "Savaitinis augimas, procentai", title = paste("Lietuvos rodikliai,", max(pld1$day)))
```


```{r}
ggplot(aes(x = tpr_dgn, y = confirmed_growth_weekly, colour = Scenario, size = population), data = pld2) +
  geom_point() +
  geom_text(aes(label = administrative_level_3), size = 4, nudge_x = 1.3, check_overlap = TRUE) +
  theme_bw() +
  scale_colour_manual(name = "100k rodiklis", values = cols) +
  scale_size_continuous(name = "Populiacija") +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 4) +
  labs(x = "Teigiama tyrim킬 dalis, procentai", y = "Savaitinis augimas, procentai", title = paste("Lietuvos rodikliai,", max(pld2$day)))
```

```{r}
ggplot(aes(x = tpr_dgn, y = confirmed_growth_weekly, colour = Scenario, size = population), data = pld3) +
  geom_point() +
  geom_text(aes(label = administrative_level_3), size = 4, nudge_x = 1.3, check_overlap = TRUE) +
  theme_bw() +
  scale_colour_manual(name = "100k rodiklis", values = cols) +
  scale_size_continuous(name = "Populiacija") +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 4) +
  labs(x = "Teigiama tyrim킬 dalis, procentai", y = "Savaitinis augimas, procentai", title = paste("Lietuvos rodikliai,", max(pld3$day)))
```
