---
title: "Weekdays"
output:
  html_document:
    df_print: paged
---

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)
Sys.setlocale(locale="lt_LT.UTF-8")
```

```{r}
lv1 <- read.csv("../data/lt-covid19-country.csv") %>% mutate(day = ymd(day))

lv11 <- lv1 %>% select(day, tests_daily, confirmed_daily,deaths_daily, tpr_tpn, tpn = tests_positive_daily, hospitalized, icu) %>% mutate(tpr = round(100*tpn/tests_daily,2), tpr2 = round(100*confirmed_daily/tests_daily,2), hospitalized_daily = hospitalized - lag(hospitalized), icu_daily = icu - lag(icu))

lv12 <- lv11 %>% mutate(week = isoweek(day), weekday = weekdays(day), wday = wday(day, week_start = 1))

wf <- lv12 %>% filter(wday %in% (1:7)) %>% slice_head(n=7) %>% arrange(wday) %>% .$weekday

lv12 <- lv12 %>% mutate(wfday = factor(weekday, levels = wf))

start_day <- "2021-01-11"

```

```{r}
ggplot(aes(x = wfday, y = tpn, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day))+geom_line()+scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) + theme_bw()+ labs(x="Savaitės diena", y = "Teigiami nauji testai", title = "Teigiami nauji testai savaitės dienomis")
```


```{r}
ggplot(aes(x = wfday, y = confirmed_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day))+geom_line()+scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) + theme_bw()+ labs(x="Savaitės diena", y = "Nauji atvejai", title = "Nauji atvejai savaitės dienomis")
```


```{r}
ggplot(aes(x = wfday, y = tests_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >=start_day))+geom_line()+scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) + theme_bw()+ labs(x="Savaitės diena", y = "Testai", title = "Testavimo apimtys savaitės dienomis")
```

```{r}
ggplot(aes(x = wfday, y = tpr, group = week, colour = as.character(week)), data = lv12 %>% filter(day>=start_day))+geom_line()+scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) + theme_bw()+ labs(x="Savaitės diena", y = "Procentai", title = "Teigiamų tyrimų dalis")
```


```{r}
ggplot(aes(x = wfday, y = tests_mobile_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day))+geom_line()+scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) + theme_bw()+ labs(x="Savaitės diena", y = "Testai mobiliuose punktuose", title = "Testavimo apimtys mobiliuose punktuose savaitės dienomis")
```

```{r}
ggplot(aes(x = wfday, y = hospitalized, group = week, colour = as.character(week)), data = lv12 %>% filter(day>=start_day))+geom_line()+scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) + theme_bw()+ labs(x="Savaitės diena", y = "Ligoniai", title = "Ligonių skaičius")
```

```{r}
ggplot(aes(x = wfday, y = icu, group = week, colour = as.character(week)), data = lv12 %>% filter(day>=start_day))+geom_line()+scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) + theme_bw()+ labs(x="Savaitės diena", y = "Ligoniai", title = "Ligonių skaičius RITS")
```
```{r}
ggplot(aes(x = wfday, y = deaths_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day))+geom_line()+scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) + theme_bw()+ labs(x="Savaitės diena", y = "Mirtys", title = "Mirčių skaičius savaitės dienomis")
```