---
title: "Covid-19 Lietuvos regionuose"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    includes:
        in_header: ga_script.html
    navbar:
      - {title: "COVID-19 Lietuvoje", href: "https://mpiktas.github.io/covid19lt/", align: right}
---


```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(lubridate)
library(DT)
library(htmltools)
Sys.setlocale(locale = "lt_LT.UTF-8")
```

Savivaldybės
=============

```{r, echo = FALSE}


dp0 <- read.csv("../data/lt-covid19-level3.csv") %>%
  mutate(day = ymd(day)) %>%
  filter(day == max(day))
cn <- read.csv("../data/lt-covid19-country.csv") %>%
  mutate(day = ymd(day)) %>%
  filter(day == max(day)) %>%
  mutate(administrative_level_3 = "Lietuva", administrative_level_2 = "Lietuva")

dp00 <- dp0 %>% bind_rows(cn)

dp <- dp00 %>%
  filter(administrative_level_3 != "Unknown") %>%
  select(Savivaldybė = administrative_level_3, Apskritis = administrative_level_2, `Atvejai_100k` = confirmed_100k, `Atvejų augimas` = confirmed_growth_weekly, `Teigiamų tyrimų dalis` = tpr_tpn, `Tyrimų dalies pokytis` = tpr_tpn_diff_weekly, `Mirtys_100k` = deaths_100k, `Mirčių augimas` = deaths_growth_weekly, `Testai_100k` = tests_100k, `Paskiepyta pirma doze (%)` = vaccinated_1_percent, `Paskiepyta (%)` = vaccinated_2_percent, Populiacija = population) %>%
  arrange(-Populiacija)


add_links <- function(x) {
  regs_n <- paste0(gsub("[.]", "", gsub(" ", "_", x)), ".html")


  links <- paste0("regions/", regs_n)

  links2 <- mapply(function(nm, hr) tags$a(href = hr, nm), x, links, SIMPLIFY = FALSE)
  sapply(links2, as.character)
}

dp$Savivaldybė <- add_links(dp$Savivaldybė)
dp$Apskritis <- add_links(dp$Apskritis)



dp %>%
  datatable(
    extensions = c("FixedColumns", "FixedHeader"),
    escape = FALSE,
    options = list(
      scrollX = TRUE,
      paging = FALSE,
      fixedHeader = TRUE
    )
  ) %>%
  formatRound(colnames(dp)[3:11], 2)
```

Apskritys
===================

```{r}

lv2 <- read.csv("../data/lt-covid19-level2.csv") %>% mutate(day = ymd(day))

dp0 <- lv2 %>% filter(day == max(day))


dp00 <- dp0 %>% bind_rows(cn)

dp <- dp00 %>%
  filter(administrative_level_2 != "Unknown") %>%
  select(Apskritis = administrative_level_2, `Atvejai_100k` = confirmed_100k, `Atvejų augimas` = confirmed_growth_weekly, `Teigiamų tyrimų dalis` = tpr_tpn, `Tyrimų dalies pokytis` = tpr_tpn_diff_weekly, `Mirtys_100k` = deaths_100k, `Mirčių augimas` = deaths_growth_weekly, `Testai_100k` = tests_100k, `Paskiepyta pirma doze (%)` = vaccinated_1_percent, `Paskiepyta (%)` = vaccinated_2_percent, Populiacija = population) %>%
  arrange(-Populiacija)

regs_n <- paste0(gsub("[.]", "", gsub(" ", "_", dp$Apskritis)), ".html")

links <- paste0("regions/", regs_n)

links2 <- mapply(function(nm, hr) tags$a(href = hr, nm), dp$Apskritis, links, SIMPLIFY = FALSE)

dp$Apskritis <- sapply(links2, as.character)


dp %>%
  datatable(
    extensions = c("FixedColumns", "FixedHeader"),
    escape = FALSE,
    options = list(
      scrollX = TRUE,
      paging = FALSE,
      fixedHeader = TRUE
    )
  ) %>%
  formatRound(colnames(dp)[2:9], 2)
```
