---
title: "COVID-19 amžiaus grupių dinamika"
output: distill::distill_article
---

```{r, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
library(lubridate)
library(zoo)
library(xts)
library(dygraphs)
library(tidyr)
Sys.setlocale(locale = "lt_LT.UTF-8")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r echo=FALSE, include=FALSE}
ad <- read.csv("../data/lt-covid19-agedist.csv")
agr <- read.csv("../raw_data/agegroups2.csv")
ag5 <- read.csv("../data/age_distribution/lt-agedist10-level3.csv")

ag5t <- ag5 %>%
  group_by(age1 = age) %>%
  summarise(population = sum(population))

ad1 <- ad %>%
  left_join(agr) %>%
  mutate(day = ymd(day)) %>%
  filter(!is.na(age1))

ad_last_day <- as.character(max(ad$day))

view_interval <- c("2021-06-01", ad_last_day)


ad2 <- ad1 %>%
  group_by(age1, day) %>%
  summarise(dd = sum(deaths_3_daily), cc = sum(confirmed_daily)) %>%
  ungroup() %>%
  arrange(age1, day) %>%
  group_by(age1) %>%
  mutate(
    dd = rollmean(dd, 7, fill = NA, align = "right"),
    cc = rollmean(cc, 7, fill = NA, align = "right")
  ) %>%
  ungroup() %>%
  inner_join(ag5t) %>%
  mutate(
    pd = dd / population * 1e6,
    pc = cc / population * 1e6
  )


ad14 <- ad1 %>%
  group_by(age1, day) %>%
  summarise(dd = sum(deaths_3_daily), cc = sum(confirmed_daily)) %>%
  ungroup() %>%
  arrange(age1, day) %>%
  group_by(age1) %>%
  mutate(
    dd = rollsum(dd, 14, fill = NA, align = "right"),
    cc = rollsum(cc, 14, fill = NA, align = "right")
  ) %>%
  ungroup() %>%
  inner_join(ag5t) %>%
  mutate(
    pd = dd / population * 1e5,
    pc = cc / population * 1e5
  )


acc <- ad2 %>% pivot_wider(id_cols = "day", names_from = age1, values_from = "cc", values_fill = 0)
xacc <- xts(acc %>% select(-day), order.by = acc$day)

pcc <- ad14 %>% pivot_wider(id_cols = "day", names_from = age1, values_from = "pc", values_fill = 0)
xpcc <- xts(pcc %>% select(-day), order.by = acc$day)

add <- ad2 %>% pivot_wider(id_cols = "day", names_from = age1, values_from = "dd", values_fill = 0)
xadd <- xts(add %>% select(-day), order.by = add$day)

pdd <- ad14 %>% pivot_wider(id_cols = "day", names_from = age1, values_from = "pd", values_fill = 0)
xpdd <- xts(pdd %>% select(-day), order.by = add$day)
```

## Gyventojų amžiaus pasiskirstymas Lietuvoje

```{r}
ggplot(aes(x = age1, y = population / 1000), data = ag5t) +
  geom_col() +
  theme_bw() +
  labs(x = "Amžiaus grupės", y = "Gyventojų skaičius, tūkst.")
```

## Atvejų skaičiai amžiaus grupėms

```{r}
dygraph(xacc[, c("0-9", "10-19", "20-29", "30-39")],
  main = "Atvejų 7 dienų slenkantis vidurkis  amžiaus grupėse <40"
) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector(dateWindow = view_interval)
```

```{r}
dygraph(xacc[, c("40-49", "50-59", "60-69", "70-79", "80+")],
  main = "Atvejų 7 dienų slenkantis vidurkis amžiaus grupėse >40"
) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector(dateWindow = view_interval)
```



```{r}
dygraph(xpcc[, c("0-9", "10-19", "20-29", "30-39")],
  main = "Atvejų skaičius 100k gyventojų per 14 dienų amžiaus grupėse <40"
) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector(dateWindow = view_interval)
```

```{r}
dygraph(xpcc[, c("40-49", "50-59", "60-69", "70-79", "80+")],
  main = "Atvejų skaičius 100k gyventojų per 14 dienų amžiaus grupėse <40"
) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector(dateWindow = view_interval)
```

## Mirčių skaičiai amžiaus grupėms

```{r}
dygraph(xadd[, c("20-29", "30-39", "40-49", "50-59")],
  main = "Mirčių 7 dienų slenkantis vidurkis amžiaus grupėse <60"
) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(4, "Set1")) %>%
  dyRangeSelector(dateWindow = view_interval)
```


```{r}
dygraph(xadd[, c("60-69", "70-79", "80+")],
  main = "Mirčių 7 dienų slenkantis vidurkis amžiaus grupėse >60"
) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")) %>%
  dyRangeSelector(dateWindow = view_interval)
```


```{r}
dygraph(xpdd[, c("20-29", "30-39", "40-49", "50-59")],
  main = "Mirčių skaičius 100k gyventojų per 14 dienų amžiaus grupėse <60"
) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(4, "Set1")) %>%
  dyRangeSelector(dateWindow = view_interval)
```

```{r}
dygraph(xpdd[, c("60-69", "70-79", "80+")],
  main = "Mirčių skaičius 100k gyventojų per 14 dienų amžiaus grupėse >60"
) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")) %>%
  dyRangeSelector(dateWindow = view_interval)
```
