---
title: "COVID-19 ligoninių statistika"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
library(readr)
library(tidyr)
library(rmarkdown)
library(lubridate)
library(DT)
library(xts)
library(dygraphs)
library(zoo)
Sys.setlocale(locale = "lt_LT.UTF-8")
```

```{r include = FALSE}
data <- Sys.time()
```

Atnaujinta: `r format(data, usetz = TRUE)`. 

```{r}

toxts <- function(d, cols) {
  out <- xts(d[, cols], order.by = d$day)
  colnames(out) <- cols
  out
}
inNA <- function(x) {
  x[x == 0] <- NA
  x
}

pivot_one <- function(d, col) {
  d1 <- d %>% pivot_wider(id_cols = "day", names_from = "region", values_from = all_of(col))
  toxts(d1, colnames(d1)[-1])
}

tlkn <- read.csv("../raw_data/tlk_nice.csv", stringsAsFactors = FALSE)
aa <- read.csv("../data/lt-covid19-country.csv") %>% mutate(day = ymd(day))
hh <- read.csv("../data/lt-covid19-hospitals-region.csv") %>%
  mutate(day = ymd(day)) %>%
  left_join(tlkn) %>%
  mutate(cv19_admissions_r7mean = ifelse(cv19_admissions_r7mean < 1000, cv19_admissions_r7mean, 0))

hhr0 <- hh %>%
  select(-healthcare_region, -hospital_name) %>%
  group_by(region, day) %>%
  summarise_all(sum)

hhr <- hhr0
colnames(hhr) <- gsub("_r7mean", "", colnames(hhr))

hha <- hh %>%
  select(-healthcare_region, -region, -hospital_name) %>%
  group_by(day) %>%
  summarise_all(sum)

cvha0 <- hha %>%
  select(day, cv19_admissions = cv19_admissions_r7mean, cv19_discharges = cv19_discharges_r7mean) %>%
  mutate_at(inNA, .vars = c("cv19_admissions", "cv19_discharges"))

cvha <- cvha0 %>% mutate(cv19_admissions = ifelse(cv19_admissions < 5000, cv19_admissions, NA))

cvhx <- toxts(aa, c("hospitalized", "icu", "ventilated", "oxygen"))
cvhax <- toxts(cvha, c("cv19_admissions", "cv19_discharges"))
colnames(cvhax) <- c("nauji", "išrašyti")

last_day <- as.character(max(aa$day))
dw <- c("2020-10-01", last_day)
```

## Pagrindinių rodiklių tendencijos

Duomenys yra sugrupuoti pagal teritorines ligonių kasas. Vilniaus duomenyse bus ir Alytus, Kauno duomenyse bus Marijampolė ir t.t.

```{r}
dygraph(cvhx[, "hospitalized"], main = "Covid-19 ligonių skaičius") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(1, 2)]) %>%
  dyRangeSelector(dateWindow = dw)
```

```{r}
dygraph(pivot_one(hhr, "cv19_hospital_beds_assigned"), main = "Covid-19 lovų skaičius, 7 dienų vidurkis") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector()
```


```{r}
dygraph(pivot_one(hhr, "cv19_hospital_beds_occupied"), main = "Covid-19 ligonių skaičius, 7 dienų vidurkis") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector()
```


```{r}
dygraph(cvhx[, "icu"], main = "Covid-19 ligonių reanimacijoje skaičius") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[1]) %>%
  dyRangeSelector(dateWindow = dw)
```

```{r}
dygraph(pivot_one(hhr, "cv19_icu_beds_assigned"), main = "Covid-19 RITS lovų skaičius, 7 dienų vidurkis") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector()
```

```{r}
dygraph(pivot_one(hhr, "cv19_icu_beds_occupied"), main = "Covid-19 RITS ligonių skaičius, 7 dienų vidurkis") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector()
```

## Priėmimo ir išrašymo dinamika

```{r}
dygraph(cvhax["2021-01-18/", 1], main = "Covid-19 naujai paguldyti ligoniai, 7 dienų vidurkis") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[1]) %>%
  dyRangeSelector()
```
```{r}
dygraph(pivot_one(hhr, "cv19_admissions")["2021-01-18/"], main = "Covid-19 naujai paguldyti ligoniai, 7 dienų vidurkis") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector() %>%
  dyCSS("left_legend.css")
```


```{r}
dygraph(cvhax["2021-01-18/", 2], main = "Covid-19 išrašyti ligoniai") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[1]) %>%
  dyRangeSelector()
```

```{r}
dygraph(pivot_one(hhr, "cv19_discharges")["2021-01-18/"], main = "Covid-19 išrašyti ligoniai, 7 dienų vidurkis") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(5, "Set1")) %>%
  dyRangeSelector() %>%
  dyCSS("left_legend.css")
```
