---
title: "COVID-19 savaitinė statistika"
output: distill::distill_article
---

```{r, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
library(lubridate)
Sys.setlocale(locale = "lt_LT.UTF-8")
```

```{r}
lv1 <- read.csv("../data/lt-covid19-country.csv") %>% mutate(day = ymd(day))

lv11 <- lv1 %>%
  select(day, tests_daily, confirmed_daily, deaths_daily, tests_mobile_daily, tpr_dgn, tpn = tests_positive_daily, hospitalized, icu, vaccinated_1_daily, vaccinated_2_daily, vaccinated_3_daily) %>%
  mutate(tpr = round(100 * tpn / tests_daily, 2), tpr2 = round(100 * confirmed_daily / tests_daily, 2), hospitalized_daily = hospitalized - lag(hospitalized), icu_daily = icu - lag(icu))

lv12 <- lv11 %>% mutate(week = isoweek(day), weekday = weekdays(day), wday = wday(day, week_start = 1), fday = floor_date(day, unit = "week", week_start = 1))

wf <- lv12 %>%
  filter(wday %in% (1:7)) %>%
  slice_head(n = 7) %>%
  arrange(wday) %>%
  .$weekday

lv12 <- lv12 %>% mutate(wfday = factor(weekday, levels = wf))


## Select exactly 5 weeks back
ff <- lv12 %>%
  filter(day >= max(lv12$day) - days(35)) %>%
  .$fday %>%
  unique() %>%
  sort()

start_day <- ff[length(ff) - 4]
```


```{r}
ggplot(aes(x = wfday, y = confirmed_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day)) +
  geom_line() +
  scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) +
  theme_bw() +
  labs(x = "Savaitės diena", y = "Nauji atvejai", title = "Nauji atvejai savaitės dienomis")
```


```{r}
ggplot(aes(x = wfday, y = tests_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day)) +
  geom_line() +
  scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) +
  theme_bw() +
  labs(x = "Savaitės diena", y = "Testai", title = "Testavimo apimtys savaitės dienomis")
```

```{r}
ggplot(aes(x = wfday, y = tpr, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day)) +
  geom_line() +
  scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) +
  theme_bw() +
  labs(x = "Savaitės diena", y = "Procentai", title = "Teigiamų tyrimų dalis")
```


```{r}
ggplot(aes(x = wfday, y = hospitalized, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day)) +
  geom_line() +
  scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) +
  theme_bw() +
  labs(x = "Savaitės diena", y = "Ligoniai", title = "Ligonių skaičius")
```

```{r}
ggplot(aes(x = wfday, y = icu, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day)) +
  geom_line() +
  scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) +
  theme_bw() +
  labs(x = "Savaitės diena", y = "Ligoniai", title = "Ligonių skaičius RITS")
```
```{r}
ggplot(aes(x = wfday, y = deaths_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day)) +
  geom_line() +
  scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) +
  theme_bw() +
  labs(x = "Savaitės diena", y = "Mirtys", title = "Mirčių skaičius savaitės dienomis")
```

```{r}
ggplot(aes(x = wfday, y = vaccinated_1_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day)) +
  geom_line() +
  scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) +
  theme_bw() +
  labs(x = "Savaitės diena", y = "Pirma vakcinos dozė", title = "Vakcinuotų pirma doze skaičius savaitės dienomis")
```

```{r}
ggplot(aes(x = wfday, y = vaccinated_2_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day)) +
  geom_line() +
  scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) +
  theme_bw() +
  labs(x = "Savaitės diena", y = "Antra vakcinos dozė", title = "Vakcinuotų antra doze skaičius savaitės dienomis")
```

```{r}
ggplot(aes(x = wfday, y = vaccinated_3_daily, group = week, colour = as.character(week)), data = lv12 %>% filter(day >= start_day)) +
  geom_line() +
  scale_colour_manual(name = "Savaitė", values = RColorBrewer::brewer.pal(5, "Set1")) +
  theme_bw() +
  labs(x = "Savaitės diena", y = "Trečia vakcinos dozė", title = "Vakcinuotų trečia doze skaičius savaitės dienomis")
```
