---
title: "Covid hospitalization data in Lithuania"
output: html_notebook
---

```{r}
library(dplyr)
library(lubridate)
library(tidyr)
cvh <- read.csv("../data/lt-covid19-hospitalized.csv") %>% mutate(day = ymd(day))
tlk <- read.csv("../data/hospital-capacity.csv") %>% mutate(day = ymd(day))

tlkt <- tlk %>% select(-tlk) %>% group_by(day, description) %>% summarise_all(sum) %>% ungroup
tlkt <- tlkt %>% 
    mutate(description = ifelse(description == "Stacionaro lovų skaičius", "number_of_beds", description)) %>% 
    mutate(description = ifelse(description == "Užimtų lovų skaičius", "beds_taken", description)) 
cvh1 <- cvh %>% mutate(description = "covid19") %>% select(-not_intensive)

hh <- bind_rows(tlkt, cvh1) %>% arrange(day, description)

perc <- function(x)round(100*x, 2)

hh1 <- hh %>% pivot_longer(total:oxygen_mask, names_to = "type", values_to = "value") %>% 
    pivot_wider(day:type, names_from ="description", values_from = "value") %>% 
    mutate(p_total = perc(covid19/number_of_beds), p_taken = perc(covid19/beds_taken))
```


```{r}
library(ggplot2)
ggplot(aes(x = day, y = p_taken, colour = type), data = hh1) + geom_line() + labs(title = "Covid19 procentas tarp užimtų lovų, 2020-10-17")
```


```{r}
library(ggplot2)
ggplot(aes(x = day, y = p_total, colour = type), data = hh1) + geom_line() + labs(title = "Covid19 procentas tarp stacionaro lovų, 2020-10-17")
```
