library(testthat)
library(gert)
source("R/download_sam.R")
source("R/download_rc.R")
source("R/download_sam_tables.R")
source("R/treat_sam.R")
source("R/treat_rc.R")
source("R/treat_hospitalization.R")

git_add("raw_data")
git_add("data")
git_commit("Update sam and rc data")
git_push()
