---
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
params: 
   region: "Klaipėdos m."
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(dygraphs)
library(ggplot2)
library(xts)
library(lubridate)
library(tidyr)
library(gridExtra)

ii <- read.csv("../data/lt-covid19-individual.csv") 

if(grepl("apskr", params$region)) {
  aa <- read.csv("../data/lt-covid19-level2.csv") %>% rename(region = administrative_level_2)
  adm <- read.csv("../raw_data/administrative_levels.csv") %>% 
    filter(administrative_level_2 == params$region)
  
  ii <- ii %>% filter(administrative_level_3 %in% adm$administrative_level_3) %>% mutate(day = ymd(day))
} else {
  if(params$region == "Lietuva") {
      aa <- read.csv("../data/lt-covid19-country.csv") %>% mutate(region = "Lietuva") 
      ii <- ii %>% mutate(day = ymd(day))
  } else {
      aa <- read.csv("../data/lt-covid19-level3.csv") %>% rename(region = administrative_level_3)
      ii <- ii %>% filter(administrative_level_3 == params$region) %>% mutate(day = ymd(day))
  }
}
fixNA <- function(x, value = 0) {
  x[is.na(x)] <- value
  x
}

last_day <- ymd(max(ii$day))


aa <- aa %>% filter(region == params$region) %>% mutate(day = ymd(day)) %>% filter(day>="2020-02-28")

aa_stats <- aa %>% select(day,confirmed_growth_weekly, confirmed_100k, tpr_confirmed, tpr_tpn,
                          tpr_confirmed_diff_weekly, tpr_tpn_diff_weekly,
                          deaths_100k, other_deaths_100k, all_deaths_100k,
                          deaths_100k_growth_weekly, other_deaths_100k_growth_weekly, all_deaths_100k_growth_weekly)

xaa <- xts(aa_stats %>% select(-day), aa_stats$day)

xi <- xts(aa %>% select(confirmed = confirmed_daily, deaths = deaths_daily, tests = tests_daily, mobile_tests = tests_mobile_daily, tpnew = tests_positive_new_daily, other_deaths = other_deaths_daily) %>% mutate(all_deaths = deaths+other_deaths), order.by = aa$day)

```

---
title: "Covid-19 `r params$region`"
---

Atvejai
=======================================================================

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Atvejų istorija

```{r}


if(nrow(xi) > 6) {
    axtt3 <- rollmean(xi, 3, fill = NA, align = "right")
    axtt7 <- rollmean(xi, 7, fill = NA, align = "right")
    colnames(axtt7) <- paste0(colnames(axtt7),"7")
    colnames(axtt3) <- paste0(colnames(axtt3),"3")
    a714 <- cbind(xi, axtt3, axtt7)
} else {
    a714 <- xi
}


dygraph(a714[,c("confirmed","confirmed3","confirmed7")], main = paste("Dieniniai atvejai ir slenkantys vidurkiai:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(3,2,1)]) %>% dyRangeSelector
```


### Nauji teigiami testai

```{r}
dygraph(a714[,c("tpnew","tpnew3","tpnew7")], main = paste("Nauji teigiami testai ir slenkantys vidurkiai:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(3,2,1)]) %>% dyRangeSelector

```


### Savaitinis augimas

```{r}
dygraph(xaa[,"confirmed_growth_weekly"], main = paste("Savaitinis atvejų augimas:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(1)]) %>% dyRangeSelector
```


### 100k dinamika

```{r}
dygraph(xaa[,"confirmed_100k"], main = paste("Atvejų skaičius 100k gyventojų per 14 dienų:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(1)]) %>% dyRangeSelector
```

Column {data-width=350}
-----------------------------------------------------------------------

### Atvejų amžiaus pasiskirstymas per pastarąsias 14 dienų

```{r}
agr <- read.csv("../raw_data/agegroups.csv")
as_all <- expand_grid(age = unique(agr$age1), sex = c("Vyras","Moteris")) %>% mutate(n1 = 0)
ii <- ii %>% filter(sex %in% c("Vyras", "Moteris"))

oo <- ii%>% filter(day >= last_day- days(13)) %>% inner_join(agr, by = "age") %>% select(-age) %>% rename(age=age1) %>% count(age, sex) %>% right_join(as_all, by = c("age", "sex")) %>% select(-n1) %>% mutate(n = fixNA(n)) %>% rename(Atvejai = n, Amžius = age) %>% pivot_wider(names_from = "sex", values_from = "Atvejai", values_fill = 0)

ld14 <- max(ii$day)-days(13)

cols<-RColorBrewer::brewer.pal(3, "Set1")

pm <- ggplot(aes(x=Amžius, y =Atvejai), data =oo %>% rename(Atvejai = Moteris)) + geom_col(fill = cols[1]) + geom_text(aes(label = Atvejai), hjust = 1.1) + coord_flip()+labs(y = "", x= "") + theme_bw() + scale_y_continuous(trans = "reverse", expand = expansion(mult=c(0.2, 0))) +  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.margin = unit(c(0.02, 0.01, 0.02, 0.02),"npc")) + labs(title = "Moterys")

pv <- ggplot(aes(x=Amžius, y =Atvejai), data =oo %>% rename(Atvejai = Vyras)) + geom_col(fill = cols[2]) + geom_text(aes(label = Atvejai), hjust = -0.1)+coord_flip()+labs(y = "", x= "") + theme_bw() + scale_y_continuous( expand = expansion(mult=c(0, 0.2)))+theme(plot.margin = unit(c(0.02, 0.02, 0.02, -0.03),"npc"), plot.title = element_text(hjust = 1)) + labs(title = "Vyrai")

grid.arrange(pm,
    pv,
    ncol=2
)
```

### Istorinis mirčių pasiskirstymas pagal amžių

```{r}
last_day <- max(ii$day)


oo <- ii%>% filter(status == "Mirė") %>% inner_join(agr, by = "age") %>% select(-age) %>% rename(age=age1) %>% count(age, sex) %>% right_join(as_all, by = c("age", "sex")) %>% select(-n1) %>% mutate(n = fixNA(n))


oo <- oo %>% rename(Atvejai = n, Amžius = age) %>% pivot_wider(names_from = "sex", values_from = "Atvejai", values_fill = 0)


pm <- ggplot(aes(x=Amžius, y =Atvejai), data =oo %>% rename(Atvejai = Moteris)) + geom_col(fill = cols[1]) + geom_text(aes(label = Atvejai), hjust = 1.1) + coord_flip()+labs(y = "", x= "") + theme_bw() + scale_y_continuous(trans = "reverse", expand = expansion(mult=c(0.13, 0))) +  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.margin = unit(c(0.02, 0.01, 0.02, 0.02),"npc")) + labs(title = "Moterys")

pv <- ggplot(aes(x=Amžius, y =Atvejai), data =oo %>% rename(Atvejai = Vyras)) + geom_col(fill = cols[2]) + geom_text(aes(label = Atvejai), hjust = -0.1)+coord_flip()+labs(y = "", x= "") + theme_bw() + scale_y_continuous( expand = expansion(mult=c(0, 0.13)))+theme(plot.margin = unit(c(0.02, 0.02, 0.02, -0.03),"npc"), plot.title = element_text(hjust = 1)) + labs(title = "Vyrai")

grid.arrange(pm,
    pv,
    ncol=2
)

```

Testai
=======================================================================

Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Naujų atvejų dalis 
```{r}
ttn1 <- 100*a714[,"confirmed"]/a714[,"tests"]

ttn7 <- 100*a714[,"confirmed7"]/a714[,"tests7"]

ttn <- cbind(ttn1, ttn7)
colnames(ttn) <- c("ttn", "ttn7")

dygraph(ttn[,c("ttn","ttn7")], main = paste("Naujų atvejų dalis testuose:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(3,1)]) %>% dyRangeSelector
```

### Teigiamų tyrimų dalis

```{r}
ttn1 <- 100*a714[,"tpnew"]/a714[,"tests"]

ttn7 <- 100*a714[,"tpnew7"]/a714[,"tests7"]

ttn <- cbind(ttn1, ttn7)
colnames(ttn) <- c("ttn", "ttn7")

dygraph(ttn[,c("ttn","ttn7")], main = paste("Teigiamų tyrimų dalis:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(3,1)]) %>% dyRangeSelector
```

### Testavimo apimtys

```{r}
dygraph(a714[,"tests"], main =  paste("Dieniniai testai ", last_day)) %>%  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[2]) %>% dyRangeSelector %>% dyBarChart
```

### Testai mobiliuose punktuose

```{r}
dygraph(a714[,"mobile_tests"], main =  paste("Dieniniai testai mobiliuose punktuose", last_day)) %>%  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[2]) %>% dyRangeSelector %>% dyBarChart
```


Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Naujų atvejų dalies augimas 

```{r}
dygraph(xaa[,"tpr_confirmed_diff_weekly"], main = paste("Naujų atvejų dalies augimas:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(1)]) %>% dyRangeSelector
```


### Teigiamų tyrimų dalies augimas

```{r}
dygraph(xaa[,"tpr_tpn_diff_weekly"], main = paste(" Teigiamų tyrimų dalies augimas:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(1)]) %>% dyRangeSelector
```


Mirtys
=======================================================================

Column {data-width=500 .tabset}
-----------------------------------------------------------------------


### Mirčių istorija

```{r}
dygraph(a714[,c("deaths","deaths7")], main = paste("Dieninės mirtys ir slenkantys vidurkiai:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(3,1)]) %>% dyRangeSelector
```

### Mirčių nuo kitų priežasčių istorija

```{r}
dygraph(a714[,c("other_deaths","other_deaths7")], main = paste("Dieninės mirtys nuo kitų priežasčių ir slenkantys vidurkiai:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(3,1)]) %>% dyRangeSelector
```

### Visų mirčių istorija

```{r}
dygraph(a714[,c("all_deaths","all_deaths7")], main = paste("Visos dieninės mirtys ir slenkantys vidurkiai:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(3,1)]) %>% dyRangeSelector
```

Column {data-width=500, .tabset}
-----------------------------------------------------------------------

### Mirčių skaičius 14 d. 100k

```{r}
dygraph(xaa[,"deaths_100k"], main = paste("Mirčių skaičius 100k gyventojų per 14 dienų:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(1)]) %>% dyRangeSelector
```

### Kitų mirčių skaičius 14 d. 100k

```{r}
dygraph(xaa[,"other_deaths_100k"], main = paste("Kitų mirčių skaičius 100k gyventojų per 14 dienų:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(1)]) %>% dyRangeSelector
```

### Visų mirčių skaičius 14 d. 100k

```{r}
dygraph(xaa[,"all_deaths_100k"], main = paste("Visų mirčių skaičius 100k gyventojų per 14 dienų:",last_day)) %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")[c(1)]) %>% dyRangeSelector
```
