on:
    workflow_dispatch:
    schedule:
        - cron: '45 10 * * *'
name: download_and_build

jobs:
  download:
    uses: ./.github/workflows/data_download.yml
  build:
    needs: download
    uses: ./.github/workflows/build_website.yml
