on:
    workflow_dispatch:
    schedule:
        - cron: '45 10 * * *'
name: download_and_build

jobs:
  download_build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: mpiktas/covid19lt/.github/workflows/data_download.yml

      - uses: mpiktas/covid19lt/.github/workflows/build_website.yml
